/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package atu_system.atu_app;

// Import classes from shared library like this
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {
    public static void main(String[] args) {
    	//String csvFile = "StudentData.CSV";
    	//Student[] students = Database.readStudent(csvFile);
    	//System.out.println(students[0].getName());
    	
        launch(args);
    }

	@Override
	public void start(Stage stage) throws Exception {
		FXMLLoader loader = new FXMLLoader();
		loader.setLocation(getClass().getResource("/WelcomeScreen.fxml"));
		Parent root = loader.load(); // Create root from FXML loader when the FXML is ready
		Scene welcomeScreen = new Scene(root);
		stage.setTitle("Automatic Teaming Up");
		
		stage.setScene(welcomeScreen);
		stage.show();
	}
}