/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package atu_system.atu_app;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

/**
 * App is the root class for the JavaFX application.
 * It would start the program and display the interface(input screen) for user to proceed.
 * 
 * @author cherry
 */
public class App extends Application {
	/**
	 * The main() serves only as fallback in case the application can not be
	 * launched through deployment artifacts. NetBeans ignores main().
	 *
	 * @param args the command line arguments
	 */
    public static void main(String[] args) {
        launch(args);
    }

    /**
	 * The start method create a root Stage object, set the scene to a welcome screen and show the scene.
	 *
	 * @param stage		the root Stage object
	 */
	@Override
	public void start(Stage stage) throws Exception {
		FXMLLoader loader = new FXMLLoader();
		loader.setLocation(getClass().getResource("/WelcomeScreen.fxml"));
		Parent root = loader.load(); // Create root from FXML loader when the FXML is ready
		Scene welcomeScreen = new Scene(root);
		stage.setTitle("Automatic Teaming Up");
		
		stage.setScene(welcomeScreen);
		stage.show();
	}
}